site_name: Orion Context Broker

docs_dir: 'docs'

pages:
- Home: 'index.md'
- Quick start guide: 'doc/manuals/quick_start_guide.md'
- Admin guide:
  - 'Build from sources': 'doc/manuals/admin/build_source.md'
  - 'Running Orion from command line': 'doc/manuals/admin/cli.md'
  - 'Database administration': 'doc/manuals/admin/database_admin.md'
  - 'Logs': 'doc/manuals/admin/logs.md'
  - 'Watchdog': 'doc/manuals/admin/watchdog.md'
  - 'Diagnosis': 'doc/manuals/admin/diagnosis.md'
  - 'Rush relayer': 'doc/manuals/admin/rush.md'
  - 'Management REST interface': 'doc/manuals/admin/management_api.md'
  - 'Data model': 'doc/manuals/admin/database_model.md'
  - 'Resources & I/O flows': 'doc/manuals/admin/resources.md'
  - 'Upgrading from previous to 0.14.1': 'doc/manuals/admin/upgrading_crossing_0-14-1.md'
  - 'Upgrading from previous to 0.19.0': 'doc/manuals/admin/upgrading_crossing_0-19-0.md'
  - 'Upgrading from previous to 0.21.0': 'doc/manuals/admin/upgrading_crossing_0-21-0.md'
- User guide:
  - 'Pagination': 'doc/manuals/user/pagination.md'
  - 'Geolocation': 'doc/manuals/user/geolocation.md'
  - 'Structured values for attributes': 'doc/manuals/user/structured_attribute_valued.md'
  - 'Context Providers registration and request forwarding': 'doc/manuals/user/context_providers.md'
  - 'Attribute metadata': 'doc/manuals/user/metadata.md'
  - 'Filtering': 'doc/manuals/user/filtering.md'
  - 'Multi tenancy': 'doc/manuals/user/multitenancy.md'
  - 'Entity service paths': 'doc/manuals/user/service_path.md'
  - 'Adding and removing attributes and entities': 'doc/manuals/user/append_and_delete.md'
  - 'Updating registrations and subscriptions': 'doc/manuals/user/updating_regs_and_subs.md'
  - 'Context Broker federation': 'doc/manuals/user/federation.md'
  - 'Duration (for registrations and subscriptions)': 'doc/manuals/user/duration.md'
  - 'Using empty types': 'doc/manuals/user/empty_types.md'
  - 'Mixing standard and convenience operations': 'doc/manuals/user/std_conv_mix.md'
  - 'HTTP and NGSI response codes': 'doc/manuals/user/http_and_ngsi_sc.md'
  - 'Security considerations': 'doc/manuals/user/security.md'
  - 'Known limitations': 'doc/manuals/user/known_limitations.md'
  - 'Forbidden characters': 'doc/manuals/user/forbidden_characters.md'
  - 'Walkthrough APIv1': 'doc/manuals/user/walkthrough_apiv1.md'
- Container-based deployment:
  - 'Vagrant': 'doc/manuals/vagrant.md'
- Sample code contributions: 'doc/manuals/code_contributions.md'
- Deprecated features: 'doc/manuals/deprecated.md'

theme: readthedocs
theme_dir: '../custom_theme'
